// <auto-generated />
using System;
using Lab2._2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2._2.Migrations
{
    [DbContext(typeof(OneMoreDBContext))]
    [Migration("20240430133206_Lab2cs5")]
    partial class Lab2cs5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2._2.Models.Nhanvien", b =>
                {
                    b.Property<int>("manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("manv"));

                    b.Property<string>("dchi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("honv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("luong")
                        .HasColumnType("real");

                    b.Property<string>("ma_nql")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("phai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phg")
                        .HasColumnType("int");

                    b.Property<string>("tenlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tennv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("manv");

                    b.ToTable("Nhanvien", "Lab22");
                });

            modelBuilder.Entity("Lab2._2.Models.Thannhan", b =>
                {
                    b.Property<int>("ma_nv")
                        .HasColumnType("int");

                    b.Property<string>("tenthannhan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("nsinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("phai")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("qhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ma_nv", "tenthannhan");

                    b.ToTable("Thannhan", "Lab22");
                });

            modelBuilder.Entity("Lab2._2.Models.Thannhan", b =>
                {
                    b.HasOne("Lab2._2.Models.Nhanvien", "Nhanvien")
                        .WithMany("thannhans")
                        .HasForeignKey("ma_nv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("Lab2._2.Models.Nhanvien", b =>
                {
                    b.Navigation("thannhans");
                });
#pragma warning restore 612, 618
        }
    }
}
